In [1]:
#1
import numpy as np
arr = np.arange(10, 50)
reshaped_arr = arr.reshape(4, 10)
last_column = reshaped_arr[:, -1]
print("Reshaped Matrix:\n", reshaped_arr)
print("\nLast Column:\n", last_column)

Reshaped Matrix:
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

Last Column:
 [19 29 39 49]


In [3]:
#2
import numpy as np

matrix_5s = np.full((3, 3), 5)
matrix_1_to_9 = np.arange(1, 10).reshape(3, 3)
sum_matrix = matrix_5s + matrix_1_to_9
product_matrix = matrix_5s * matrix_1_to_9
transpose_product = product_matrix.T
print("Matrix of 5s:\n", matrix_5s)
print("\nMatrix 1 to 9:\n", matrix_1_to_9)
print("\nSum:\n", sum_matrix)
print("\nElement-wise Product:\n", product_matrix)
print("\nTranspose of Product:\n", transpose_product)

Matrix of 5s:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

Matrix 1 to 9:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Element-wise Product:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]

Transpose of Product:
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [4]:
#3
import numpy as np
arr = np.random.randint(10, 101, size=15)
replaced_arr = arr.copy()
replaced_arr[replaced_arr > 50] = -1
count_replaced = np.sum(arr > 50)
print("Original Array:\n", arr)
print("\nModified Array:\n", replaced_arr)
print("\nNumber of values replaced:", count_replaced)


Original Array:
 [81 67 50 45 32 12 73 67 33 56 62 72 22 91 99]

Modified Array:
 [-1 -1 50 45 32 12 -1 -1 33 -1 -1 -1 22 -1 -1]

Number of values replaced: 9


In [5]:
#4
import numpy as np
array = np.random.rand(5, 4)
print("Original Array:\n", array)
row_sums = np.sum(array, axis=1)
max_row_index = np.argmax(row_sums)
print("\nRow with maximum sum is at index:", max_row_index)
print("Maximum sum value:", row_sums[max_row_index])
print("Row with max sum:", array[max_row_index])

normalized_array = np.zeros_like(array)

for i in range(array.shape[0]):
    row = array[i]
    row_min = np.min(row)
    row_max = np.max(row)
    normalized_array[i] = (row - row_min) / (row_max - row_min)

print("\nNormalized Array:\n", normalized_array)


Original Array:
 [[0.3361925  0.242423   0.04979059 0.47869124]
 [0.63740576 0.81787539 0.45993365 0.50053364]
 [0.67780266 0.64133718 0.79003158 0.60145612]
 [0.28511393 0.0343988  0.59795333 0.62535308]
 [0.41792939 0.28662584 0.72800807 0.34172364]]

Row with maximum sum is at index: 2
Maximum sum value: 2.710627538906543
Row with max sum: [0.67780266 0.64133718 0.79003158 0.60145612]

Normalized Array:
 [[0.66775816 0.4491306  0.         1.        ]
 [0.49581283 1.         0.         0.11342626]
 [0.40485938 0.21148596 1.         0.        ]
 [0.4242547  0.         0.95363474 1.        ]
 [0.29748263 0.         1.         0.12483012]]


In [6]:
#5
import numpy as np

arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])

unique, counts = np.unique(arr, return_counts=True)


duplicates = unique[counts > 1]
print("Duplicate elements:", duplicates)


Duplicate elements: [1 3 5]


In [7]:
#6
import numpy as np

array = np.arange(1, 37).reshape(6, 6)
print("Original 6x6 Array:\n", array)
submatrix_4x4 = array[1:5, 1:5]
print("\nMiddle 4x4 Submatrix:\n", submatrix_4x4)
even_numbers = submatrix_4x4[submatrix_4x4 % 2 == 0]
print("\nEven numbers in the submatrix:\n", even_numbers)


Original 6x6 Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Middle 4x4 Submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]

Even numbers in the submatrix:
 [ 8 10 14 16 20 22 26 28]


In [8]:
#7
import numpy as np

array = np.arange(12).reshape(3, 4)
print("Original (3,4) Array:\n", array)
reshaped_2x6 = array.reshape(2, 6)
print("\nReshaped to (2,6):\n", reshaped_2x6)
flattened = reshaped_2x6.flatten()
print("\nFlattened 1D Array:\n", flattened)
reshaped_4x3 = flattened.reshape(4, 3)
print("\nReshaped back to (4,3):\n", reshaped_4x3)



Original (3,4) Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to (2,6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Flattened 1D Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped back to (4,3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [12]:
#8
import numpy as np

a = np.array([[1, 2], [3, 4]])
print("Original array:\n", a)

a = np.vstack([a, [5, 6]])
print("After adding row [5, 6]:\n", a)

new_col = np.array([[7], [8], [9]])
a = np.hstack([a, new_col])
print("After adding column [7, 8, 9]:\n", a)





Original array:
 [[1 2]
 [3 4]]
After adding row [5, 6]:
 [[1 2]
 [3 4]
 [5 6]]
After adding column [7, 8, 9]:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [13]:
#9
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

combined = np.concatenate([a, b, c])
print("Combined array:\n", combined)


matrix = combined.reshape(3, 3)
print("Reshaped 3x3 matrix:\n", matrix)

diagonal = np.diag(matrix)
print("Diagonal elements:\n", diagonal)


Combined array:
 [1 2 3 4 5 6 7 8 9]
Reshaped 3x3 matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal elements:
 [1 5 9]


In [14]:
#10
import numpy as np
arr = np.arange(1, 21)
print("Original array:\n", arr)

filtered = arr[(arr % 3 == 0) | (arr % 5 == 0)]
print("Values divisible by 3 or 5:\n", filtered)

count = filtered.size
print("Count of values divisible by 3 or 5:", count)


Original array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Values divisible by 3 or 5:
 [ 3  5  6  9 10 12 15 18 20]
Count of values divisible by 3 or 5: 9
